/* Chinese UI strings for the Site Manager (admin.html). Keys are the English texts as they appear in the page
 * (text nodes, placeholders, titles, aria-labels), applied at runtime by SiteLang.translator(). Content you typed
 * (names, titles, notes) is never translated, only the interface around it. */
window.ADMIN_ZH = {
  // shell
  'Site Manager': '站点管理', 'Not signed in': '未登录', 'Sign out': '退出登录', 'Open website ↗': '打开网站 ↗', 'Loading…': '加载中…',
  'Reload from GitHub': '从 GitHub 重新加载', 'Publish changes': '发布更改', 'Publish now': '立即发布', 'Unpublished changes': '有未发布的更改', 'Already published.': '已全部发布。',
  'Up to date': '已是最新', 'Read-only (not signed in)': '只读（未登录）', 'Read-only preview (no token)': '只读预览（无令牌）', 'Loading from GitHub…': '正在从 GitHub 加载…',
  'Checking sign-in…': '正在检查登录…', 'Switch to dark mode': '切换到深色模式', 'Switch to light mode': '切换到浅色模式', 'Could not load content.json': '无法加载 content.json',
  'Visitors': '访客', 'Profile': '个人资料', 'Research interests': '研究方向', 'Education': '教育经历', 'Publications': '论文', 'Awards': '奖项', 'Photos': '照片',
  'Footprints': '足迹', 'Flights': '飞行', 'CV & site settings': '简历与站点设置', 'Raw JSON': '原始 JSON',
  // sign-in
  'Sign in': '登录', 'Password': '密码', 'Keep me signed in on this device': '在此设备上保持登录', 'Sign in with a GitHub token': '使用 GitHub 令牌登录', 'View read-only': '只读查看',
  '← Back to website': '← 返回网站', 'Sign in with a token': '使用令牌登录', 'GitHub token': 'GitHub 令牌', 'How to create the GitHub token': '如何创建 GitHub 令牌',
  'GitHub → Settings → Developer settings → Personal access tokens →': 'GitHub → Settings → Developer settings → Personal access tokens →', 'Fine-grained tokens': 'Fine-grained tokens',
  '→ Generate new token': '→ Generate new token', 'Repository access:': '仓库访问：', 'Only select repositories': 'Only select repositories', 'Permissions:': '权限：',
  '+ Add permissions': '+ Add permissions', '→ Contents →': '→ Contents →', 'Read and write': 'Read and write', 'Contents: Read and write': 'Contents: Read and write',
  'Generate, copy the token and paste it here': '生成后复制令牌粘贴到这里', 'Use password instead': '改用密码登录', 'Back to password sign-in': '返回密码登录',
  'Set up password sign-in': '设置密码登录', 'Paste your GitHub token once and choose a password. The token is encrypted with the password and saved in the repository, so you can sign in on any device with the password alone.': '粘贴一次 GitHub 令牌并设置密码。令牌会用密码加密后保存在仓库里，之后在任何设备上只需密码即可登录。',
  'New password': '新密码', 'Repeat password': '重复密码', 'Repeat': '重复', 'Create sign-in': '创建登录', 'Create': '创建', 'Cancel': '取消', 'Try again': '重试', 'Sign in again instead': '改为重新登录',
  "Can't reach GitHub": '无法连接 GitHub', 'The sign-in settings could not be loaded (slow network, GitHub busy, or too many requests in a short time). Wait a minute and try again.': '无法加载登录设置（网络慢、GitHub 繁忙或短时间请求过多）。请稍等一分钟再试。',
  'Sign-in created. From now on, use your password on any device.': '登录已创建。今后在任何设备上使用密码即可。', 'Password sign-in on': '密码登录已开启', 'Password sign-in off': '密码登录已关闭',
  'Password sign-in turned off. Sign in with a token from now on.': '密码登录已关闭，今后请使用令牌登录。', 'Turn off password sign-in': '关闭密码登录', 'Current password': '当前密码',
  'Replace GitHub token (optional)': '更换 GitHub 令牌（可选）', 'leave empty to keep the current token': '留空则保留当前令牌', 'Use this when the token expires. The GoatCounter token from the Visitors tab is saved along with it.': '令牌过期时使用。访客页的 GoatCounter 令牌会一并保存。',
  'You are signed in with a token. Set a password to sign in from any device.': '你当前以令牌登录。设置密码后可在任何设备登录。', 'Admin sign-in': '管理员登录', 'Sign in to manage the password.': '登录后可管理密码。',
  'Sign in with a GitHub token to publish.': '使用 GitHub 令牌登录后才能发布。', 'Sign in to upload images.': '登录后才能上传图片。', 'Sign in with a token to upload files.': '使用令牌登录后才能上传文件。',
  'If you just set up the site, make sure content.json exists in the repository root, and that the token has': '如果你刚建好站点，请确认仓库根目录有 content.json，并且令牌拥有', 'permission for this repository.': '对该仓库的权限。',
  // visitors
  'Aggregate, privacy-friendly statistics from GoatCounter: page views, countries and referrers. No individual IP addresses are stored or shown.': '来自 GoatCounter 的汇总统计，注重隐私：页面浏览量、国家和来源。不存储也不显示任何个人 IP。',
  'GoatCounter API token (read statistics)': 'GoatCounter API 令牌（读取统计）', 'stored in this browser only': '仅保存在此浏览器', 'Save': '保存', 'Open dashboard ↗': '打开仪表盘 ↗', 'Google Analytics ↗': 'Google Analytics ↗',
  '7 days': '7 天', '30 days': '30 天', '90 days': '90 天', '1 year': '1 年', 'Page views': '页面浏览量', 'last 30 days, all pages': '最近 30 天，全部页面', 'Homepage': '主页', '/ and index.html': '/ 与 index.html',
  'Publications page': '论文页', 'Unlock the map, countries and trends': '解锁地图、国家与趋势', 'API token': 'API 令牌',
  "The numbers above are public counters. The world map, the country list, referrers and the daily chart come from GoatCounter's statistics API, which needs an": '上面的数字是公开计数。世界地图、国家列表、来源和每日图表来自 GoatCounter 的统计 API，需要一个',
  ': a password-like key that lets this page read your statistics (read only, it cannot change anything).': '：一个类似密码的密钥，让本页读取你的统计（只读，无法更改任何内容）。',
  'Open': '打开', 'Click': '点击', 'New API token': 'New API token', ', give it a name such as': '，取一个名字，如', 'site manager': 'site manager', ', and tick': '，并只勾选', 'Read statistics': 'Read statistics', 'only.': '。',
  'Create it, copy the token, paste it into the box above and click': '创建后复制令牌，粘贴到上面的输入框并点击', 'in GoatCounter.': '。',
  'If you are signed in with your password, the token is saved inside your encrypted sign-in, so it works on every device. If the counts stay at “–”, enable': '如果你用密码登录，令牌会保存在加密的登录信息中，在每台设备上都可用。如果计数一直显示“–”，请在 GoatCounter 中开启',
  'Settings → Allow adding visitor counts on your website': 'Settings → Allow adding visitor counts on your website',
  'Daily page views': '每日浏览量', 'Visitors by country': '按国家的访客', 'World map of page views by country': '各国页面浏览量世界地图', 'Referrers': '来源', 'Pages': '页面', 'Countries': '国家',
  'No data in this period.': '该时段没有数据。', 'No visits': '没有访问', 'views': '次浏览', 'Wikipedia page views, last 60 days': '维基百科页面浏览量，最近 60 天',
  'No visits recorded yet. GoatCounter only counts visits after the tracking script is live: check that the site code is published under': '还没有记录到访问。GoatCounter 只统计跟踪脚本上线后的访问：请确认站点代码已发布在',
  ', then open the website once and come back in a few minutes. Your own visits from this browser may be ignored if you enabled that in GoatCounter.': '，然后打开一次网站，几分钟后再回来。如果你在 GoatCounter 中设置了忽略自己的访问，本浏览器的访问不会计入。',
  'Set up GoatCounter (free, ~3 minutes)': '设置 GoatCounter（免费，约 3 分钟）', 'Create an account at': '在此注册账号：', 'and pick a site code (e.g.': '并选择一个站点代码（如', 'Enter that code under': '把代码填到',
  'CV & site settings → GoatCounter site code': '简历与站点设置 → GoatCounter 站点代码', 'and publish. Both pages then load the tracking script.': '然后发布。两个页面随即加载跟踪脚本。',
  'For charts here: GoatCounter → Settings →': '若要在这里看图表：GoatCounter → Settings →', '→ new token with': '→ 新建令牌并勾选', 'permission. You can always open the GoatCounter dashboard directly.': '权限。你也随时可以直接打开 GoatCounter 仪表盘。',
  // profile
  'The hero section at the top of the homepage.': '主页顶部的个人信息区。', 'Name (English)': '姓名（英文）', 'Name (中文)': '姓名（中文）', 'Photo file': '照片文件',
  'File name in the repository root, e.g. photo.jpg. Upload a new one below.': '仓库根目录中的文件名，如 photo.jpg。可在下方上传新照片。', 'Upload new photo…': '上传新照片…', 'Affiliation line': '单位一行',
  'Short bio': '简介', 'Email': '邮箱', 'Shown as an obfuscated mailto button. Leave empty to hide.': '显示为防爬的邮件按钮。留空则隐藏。', 'Profile links': '个人链接', 'Label': '标签', 'Icon': '图标', 'URL': '网址',
  '+ Add link': '+ 添加链接', 'English': '英文', 'Move up': '上移', 'Move down': '下移', 'Move left': '左移', 'Move right': '右移', 'Remove': '删除', 'Delete': '删除', 'Edit': '编辑', 'Discard': '放弃', 'Clear': '清除', 'Find': '查找', 'Search': '搜索', 'Sort': '排序', 'Import': '导入', 'Paste': '粘贴', 'Upload': '上传', 'Uploading…': '上传中…',
  'leave empty to hide': '留空则隐藏', 'optional': '可选', 'none': '无', 'public': '公开', 'image': '图片', 'here': '这里', 'heading': '标题', 'Webpage': '网页', 'Type': '类型', 'Code': '代码', 'Name or code': '名称或代码',
  // research / education
  'Tag pills on the homepage, in display order.': '主页上的标签胶囊，按显示顺序。', '+ Add interest': '+ 添加方向', 'Timeline entries, newest first.': '时间线条目，最新在前。', 'Period': '时间', 'Logo': '校徽', 'Logo tooltip': '校徽提示',
  'Degree': '学位', 'School': '学校', 'Supervisors': '导师', '+ Add supervisor': '+ 添加导师', '+ Add entry': '+ 添加条目', 'Name (EN)': '姓名（英文）', 'No logo yet': '还没有校徽',
  'Upload a logo image (PNG, JPG, WebP or SVG). It is resized to 240 px and saved in the repository.': '上传校徽图片（PNG、JPG、WebP 或 SVG），会缩放到 240 px 并保存到仓库。',
  '2025-07, 2018-2025, or blank': '2025-07、2018-2025 或留空',
  // publications
  'Click a paper to edit. Papers are grouped by year on both pages; the collaboration network and the summary counts are computed from this list automatically.': '点击论文进行编辑。两个页面都按年份分组；合作网络和统计数字由此列表自动计算。',
  'Add from DOI': '通过 DOI 添加', 'Fetch & add': '抓取并添加', '+ Add manually': '+ 手动添加', 'Add manually': '手动添加', 'Upload journal cover…': '上传期刊封面…', 'Journal cover': '期刊封面',
  '↻ Refresh citations, abstracts & covers': '↻ 刷新引用、摘要与封面', 'Update citation counts, fill in missing DOIs and abstracts, publish, and fetch missing journal covers': '更新引用数、补全缺失的 DOI 与摘要，发布，并抓取缺失的期刊封面',
  'Abstract sources (optional Elsevier key)': '摘要来源（可选 Elsevier 密钥）', 'Elsevier API key': 'Elsevier API 密钥', '32 characters': '32 个字符', 'fixes that: register at': '可以解决：在', 'Create API Key': 'Create API Key',
  ', paste it here. It is stored in your encrypted sign-in, so it works on every device. For the GitHub cover-and-abstract workflow, also add it as the repository secret': '，粘贴到这里。它保存在加密的登录信息中，每台设备都可用。若要用 GitHub 的封面与摘要工作流，也请把它添加为仓库 secret',
  'First author': '第一作者', 'First Author': '第一作者', 'Corresponding': '通讯作者', 'Corresponding Author': '通讯作者', 'Under Revision': '修改中', 'Featured': '精选', 'Status badge': '状态标签', 'Books': '著作', 'Citations': '引用', 'Abstract': '摘要', 'No abstract': '没有摘要',
  'No abstract yet: click Refresh, or open the paper and paste one': '还没有摘要：点击刷新，或打开论文粘贴一段', 'Under Review / In Prep / empty': 'Under Review / In Prep / 留空', '2025 or book': '2025 或 book',
  'Refill from DOI': '按 DOI 重新填写', 'Refill replaces title, authors, venue, link, year, abstract and citation count; flags, status and cover are kept.': '重新填写会替换标题、作者、期刊、链接、年份、摘要和引用数；标记、状态和封面保留。',
  'Refilled from DOI. Review, then publish.': '已按 DOI 重新填写。请检查后发布。', 'Cover uploaded. Publish to save.': '封面已上传。发布以保存。', 'Click, then press Ctrl+V / ⌘V to paste an image': '点击后按 Ctrl+V / ⌘V 粘贴图片',
  '…or paste an image URL (https://…/cover.jpg)': '…或粘贴图片网址（https://…/cover.jpg）', 'Enter a full image URL starting with https://': '请输入以 https:// 开头的完整图片网址',
  'The clipboard has no image. Copy the cover image first.': '剪贴板里没有图片。请先复制封面图片。', 'The image is larger than 10 MB.': '图片超过 10 MB。', 'File is larger than 20 MB.': '文件超过 20 MB。',
  'e.g. Biodiversity footprints of global trade': '例如 Biodiversity footprints of global trade', 'Crossref…': 'Crossref…', 'OpenAlex…': 'OpenAlex…', 'Semantic Scholar…': 'Semantic Scholar…', 'Europe PMC…': 'Europe PMC…', 'Elsevier…': 'Elsevier…',
  // awards / photos
  'Selected awards': '所获奖项', 'Listed in display order. “Highlight” gives the row the emphasised style; “Note” is the small tag (e.g. Top 1%).': '按显示顺序排列。“高亮”使该行使用强调样式；“备注”是小标签（如 Top 1%）。',
  'Year': '年份', 'Award (EN)': '奖项（英文）', 'Note': '备注', 'Highlight': '高亮', '+ Add award': '+ 添加奖项',
  'Photo carousels': '照片轮播', 'Two photo strips on the homepage. Captions get “Photo by Hui Tang” appended automatically.': '主页上的两条照片带。图注会自动加上“摄影”后缀。', 'Photo credit suffix': '摄影署名后缀',
  'Carousel 1 (after Education)': '轮播 1（教育经历之后）', 'Carousel 2 (after Publications)': '轮播 2（论文之后）', 'Upload photo…': '上传照片…', 'Upload photos…': '上传照片…', 'Caption (EN)': '图注（英文）', 'No photos yet.': '还没有照片。', 'Photo deleted.': '照片已删除。',
  // footprints
  'One list of places for two pages.': '一份地点列表，供两个页面使用。', 'shows everything and opens only with the': '显示全部内容，仅凭', 'travel password': '旅行密码', 'Travel password': '旅行密码',
  '(share it with family and friends; it gives no access to this manager). Entries ticked as': '打开（可分享给家人朋友；它无法进入本管理页）。勾选为', 'academic visit': '学术访问', 'are also published, in clear, on the public': '的条目还会明文发布到公开的',
  'Sign in to edit the footprints.': '登录后可编辑足迹。', 'Set up the footprint pages': '设置足迹页面', 'New travel password': '新的旅行密码', 'Change travel password': '更改旅行密码',
  'Share this password with the people who may see travel.html. Changing it only re-encrypts the list; the photos stay as they are.': '把这个密码分享给可以查看 travel.html 的人。更改密码只会重新加密列表，照片保持不变。',
  'Travel password changed. Anyone with the old password can no longer open travel.html.': '旅行密码已更改。持旧密码的人无法再打开 travel.html。', 'Travel password set, but it could not be saved into your sign-in:': '旅行密码已设置，但无法保存到你的登录信息：',
  'Created. Add your first place below.': '已创建。在下方添加第一个地点。', 'Add a place': '添加地点', 'New place': '新地点', 'Places': '地点', 'City or town': '城市或城镇', 'e.g. Groningen, Lhasa, Kyoto': '例如 Groningen、拉萨、京都',
  'Find a place: city, country, conference, sight … (中文 or English)': '查找地点：城市、国家、会议、景点…（中文或英文）', 'Nothing yet. Search for a city above.': '还没有内容。在上方搜索城市。', 'Give the place a name first': '请先给地点命名',
  'Fill in the details, then add it to the list below.': '填写详情，然后添加到下方列表。', '✓ Done, add to the list': '✓ 完成，添加到列表', '+ Add another visit': '+ 添加另一次访问', 'When': '时间', 'Latitude': '纬度', 'Longitude': '经度',
  'A month (2025-07), a year or a range (2018-2025, 2025 - present). Several visits: separate with “;”, e.g. 2019-05; 2023-08.': '月份（2025-07）、年份或区间（2018-2025、2025 - present）。多次访问用“;”分隔，如 2019-05; 2023-08。',
  'Academic': '学术', 'Personal': '个人', 'Presentation': '报告', 'Purpose': '目的', 'Icon (map marker and list)': '图标（地图标记与列表）', 'Other (type it in)…': '其他（自行输入）…',
  'Academic page (public)': '学术页（公开）', 'Travel page (private)': '旅行页（私密）', 'Open academic.html ↗': '打开 academic.html ↗', 'Open travel.html ↗': '打开 travel.html ↗',
  'Only the academic part is public: the conference details, the public note, and the photos and sights marked': '只有学术部分是公开的：会议详情、公开备注，以及标记为', '🌐 public (academic)': '🌐 公开（学术）', '🔒 private (travel only)': '🔒 私密（仅旅行页）',
  '. Everything else (trip type, private note, private photos and sights) appears on the travel page only.': '的照片和景点。其余内容（旅行类型、私密备注、私密照片和景点）只出现在旅行页。',
  'or drag photos onto this place': '或将照片拖到此地点', '; photos upload immediately.': '；照片会立即上传。', 'Find landmarks nearby': '查找附近地标', 'or search by name, e.g. 外滩': '或按名称搜索，如 外滩',
  'No sights yet. Search nearby or add one by hand; tick the ones you visited.': '还没有景点。搜索附近或手动添加；勾选你去过的。', 'Nothing found within 50 km on Wikidata. Add the sight by hand.': 'Wikidata 上 50 km 内没有结果。请手动添加景点。',
  'Landmark search uses Wikidata and the built-in UNESCO list. Wikidata is blocked in mainland China, so for Chinese places add a free': '地标搜索使用 Wikidata 和内置的 UNESCO 列表。Wikidata 在中国大陆无法访问，所以中国地点请添加一个免费的',
  'Amap (高德) Web-service key': '高德 Web 服务 key', 'Amap Web-service key': '高德 Web 服务 key', 'Web服务': 'Web服务', '. The key is stored inside your encrypted sign-in.': '。密钥保存在加密的登录信息中。',
  'Untick to remove': '取消勾选即删除', 'Shown when visitors hover this sight': '访客悬停此景点时显示', 'Shown even while its country is collapsed on the pages, with a star': '页面上即使所在国家折叠也会显示，并带星标',
  'official site (optional; otherwise Baike / Wikipedia is used)': '官网（可选；否则使用百科 / 维基百科）', 'for sight': '景点', 'most known': '最知名', 'nearest': '最近', 'is the property itself': '即遗产地本身', 'is the 5A area itself': '即 5A 景区本身',
  'World Heritage': '世界遗产', '5A area': '5A 景区', 'Not part of a World Heritage property': '不属于世界遗产地', 'Not part of a bundled 5A area': '不属于打包的 5A 景区',
  'Counted once, under this World Heritage property': '只计一次，归入此世界遗产地', 'Counted once, under this 5A scenic area': '只计一次，归入此 5A 景区', 'Nearest component of this serial property': '此系列遗产中最近的组成部分',
  '✓ Check all tags': '✓ 检查全部标签', 'Re-checks every saved sight: 5A against the official list (358, May 2025), national parks against the official rule, and World Heritage / 5A-area grouping. Tags you set by hand are checked too.': '重新检查每个已保存的景点：5A 对照官方名单（358 个，2025 年 5 月），国家公园对照官方规则，以及世界遗产 / 5A 景区归并。手动设置的标签也会检查。',
  'Translate names': '翻译名称', 'Fill in or redo the English names of Chinese sights': '补全或重做中国景点的英文名', 'Loading the official lists…': '正在加载官方名单…', 'Loading map…': '正在加载地图…', 'Expand all': '全部展开', 'Collapse all': '全部折叠',
  'Newest first': '最新在前', 'Flags': '国旗',
  // flights
  'The flight log is stored encrypted together with the footprints and opens with the same': '飞行记录与足迹一起加密存储，使用同一个', 'on': '打开', 'Loading the airport and airline lists…': '正在加载机场和航司列表…', 'Could not load the airport list:': '无法加载机场列表：',
  'Find a flight: number, airport, airline, aircraft, year …': '查找航班：航班号、机场、航司、机型、年份…', 'Date': '日期', 'Flight number': '航班号', 'From': '出发', 'To': '到达', 'Airline': '航空公司', 'Aircraft': '机型', 'Registration': '注册号', 'Seat': '座位', 'Class': '舱位',
  'Fare': '票价', 'Currency': '货币', 'Flight time (h:mm)': '飞行时长（h:mm）', 'Actual take-off': '实际起飞', 'Actual landing': '实际降落', 'Aircraft age (years)': '机龄（年）',
  'IATA code or city, e.g. AMS': 'IATA 代码或城市，如 AMS', 'IATA code or city, e.g. PEK': 'IATA 代码或城市，如 PEK', 'Amsterdam (AMS/EHAM)': '阿姆斯特丹（AMS/EHAM）', 'Aircraft type, e.g. Ilyushin Il-96': '机型，如 Ilyushin Il-96',
  'The airline is filled in from the first two characters.': '航司由前两个字符自动填入。', 'optional, e.g. PH-BKA': '可选，如 PH-BKA', 'optional, e.g. 32K': '可选，如 32K', 'optional, e.g. 3280': '可选，如 3280', 'optional, e.g. 8.5 or 2016': '可选，如 8.5 或 2016', 'optional, e.g. 9:50': '可选，如 9:50',
  'local, e.g. 09:35': '当地时间，如 09:35', 'local, e.g. 06:10+1': '当地时间，如 06:10+1', 'Choose a date.': '请选择日期。', 'Choose both airports from the suggestions.': '请从建议中选择两个机场。', 'From and To are the same airport.': '出发和到达是同一个机场。',
  'Take-off time: write it like 09:35.': '起飞时间：请写成 09:35。', 'Landing time: write it like 14:10, or 06:10+1 for the next day.': '降落时间：请写成 14:10，次日则写 06:10+1。', 'Fare: write a number, e.g. 3280.': '票价：请填数字，如 3280。',
  'Aircraft age: write the years (8.5) or the year it was built (2016).': '机龄：填年数（8.5）或出厂年份（2016）。', 'Flight updated. Publish to save.': '航班已更新。发布以保存。',
  '⬇ Export CSV': '⬇ 导出 CSV', 'Download every flight as a CSV (re-importable here)': '把全部航班下载为 CSV（可在此重新导入）', 'Choose a CSV file…': '选择 CSV 文件…', 'Paste a CSV with a header row. Recognised columns:': '粘贴带表头的 CSV。可识别的列：',
  'Merge duplicates': '合并重复', 'Keeps one of each, with any details only the copies had.': '每组只保留一条，并补上副本独有的信息。', 'Same flight number, date and route': '相同航班号、日期和航线', 'Same flight number, same day, same airports:': '相同航班号、同一天、相同机场：', 'no duplicates': '没有重复',
  '. Airports may be written as IATA codes (': '。机场可写 IATA 代码（', ') or like': '）或写成', '; aircraft by name or ICAO code (': '；机型可写名称或 ICAO 代码（', 'adds the actual times to existing flights. A reason of “business” or “academic” marks the flight as academic.': '会把实际时间补到已有航班上。目的为“business”或“academic”时标记为学术飞行。',
  // cv & settings
  'The CV download card, page titles, analytics IDs and your admin sign-in.': '简历下载卡片、页面标题、统计 ID 和管理员登录。', 'Curriculum vitae': '简历', 'CV file name': '简历文件名', 'PDF in the repository root. Spaces are fine.': '仓库根目录中的 PDF，文件名可含空格。',
  'Upload new CV (PDF)…': '上传新简历（PDF）…', '“Last updated” line': '“最近更新”一行', 'Site': '站点', 'Homepage title': '主页标题', 'Publications page title': '论文页标题', 'Footer year': '页脚年份', 'Your author short name': '你的作者简称',
  'As written in author lists, e.g. Tang H. This name sits at the centre of the network graph.': '作者列表中的写法，如 Tang H.。该名字位于合作网络图的中心。', 'Analytics': '统计分析', 'GoatCounter site code': 'GoatCounter 站点代码', 'The': '即',
  'in xxx.goatcounter.com. Leave empty to disable. Pageviews only, no cookies, no personal data.': '（xxx.goatcounter.com 中的 xxx）。留空则关闭。只统计浏览量，无 Cookie，无个人数据。', 'Google Analytics ID': 'Google Analytics ID', 'Informational: the GA tag is in the page head.': '仅供参考：GA 标签位于页面 head 中。',
  'Colours': '配色', 'Colour scheme of every public page, in light and dark mode (and of this Site Manager, as a preview). Saved with': '所有公开页面在浅色和深色模式下的配色（本管理页同步预览）。随', 'Light mode': '浅色模式', 'Dark mode': '深色模式', 'View publications': '查看论文',
  'The current look. Navy ink, ocean-blue accent.': '当前外观。藏青文字，海蓝强调色。', 'Brighter sky blue, crisp and airy.': '更明亮的天蓝，清爽通透。', 'Teal and sea green, calm and fresh.': '青绿与海绿，平静清新。', 'Deep green for ecology and conservation.': '深绿，呼应生态与保护。',
  'Quiet slate greys, minimal and neutral.': '安静的石板灰，极简中性。', 'The site’s original warm look: walnut brown on warm paper.': '站点最初的暖色外观：暖纸底上的胡桃棕。', 'Deep Peking University red, formal and classic.': '深北大红，正式而经典。',
  'Fonts': '字体', 'Used on every public page: homepage, publications, academic and travel maps. Saved with': '用于所有公开页面：主页、论文、学术与旅行地图。随', '(as': '（即', '); visitors see it after GitHub Pages updates.': '）保存；GitHub Pages 更新后访客可见。',
  'English: headings + body': '英文：标题 + 正文', 'Chinese: headings + body': '中文：标题 + 正文', 'Text size': '文字大小', 'Biodiversity and global trade': 'Biodiversity and global trade',
  'Crimson Pro + DM Sans. The original pairing. Warm book serif, soft geometric sans.': 'Crimson Pro + DM Sans。最初的搭配：温暖的书籍衬线体与柔和的几何无衬线体。',
  'Source Serif 4 + Source Sans 3. Scholarly pair from Adobe. Calm and readable at small sizes.': 'Source Serif 4 + Source Sans 3。Adobe 的学术搭配，平和，小字号也易读。',
  'Newsreader + Public Sans. Journal-like headings with a neutral, sturdy body.': 'Newsreader + Public Sans。期刊风格的标题，中性结实的正文。', 'EB Garamond + Work Sans. Classic Garamond, the most traditional feel.': 'EB Garamond + Work Sans。经典 Garamond，最传统的气质。',
  'IBM Plex Serif + IBM Plex Sans. One family, engineered look. Suits data-heavy research.': 'IBM Plex Serif + IBM Plex Sans。同一家族，工程感，适合数据密集的研究。', 'Literata + Figtree. Made for long reading on screens. Friendly and modern.': 'Literata + Figtree。为屏幕长阅读而生，友好现代。',
  'site-theme.js is missing from the repository, so fonts cannot be chosen here. Upload it to the repository root.': '仓库中缺少 site-theme.js，无法在此选择字体。请上传到仓库根目录。',
  // json / publish
  'The full content.json. Edit carefully; “Apply” validates before replacing the working copy.': '完整的 content.json。请谨慎编辑；“应用”会先校验再替换工作副本。', 'Apply to working copy': '应用到工作副本', '(or use Publish changes at the top)': '（或使用顶部的“发布更改”）',
  'Published. GitHub Pages usually updates within a minute.': '已发布。GitHub Pages 通常一分钟内更新。',
  'Title, authors, journal, volume/pages, year, abstract and citation count are filled in from Crossref, OpenAlex and Semantic Scholar. Check the author list (corresponding author *) and the status badge afterwards.': '标题、作者、期刊、卷/页、年份、摘要和引用数会从 Crossref、OpenAlex 和 Semantic Scholar 自动填入。之后请检查作者列表（通讯作者 *）和状态标签。',
  'Abstracts come from Crossref, OpenAlex, Semantic Scholar and Europe PMC, which are free but do not carry the abstracts of most Elsevier journals (Applied Geography, Landscape and Urban Planning, Ecosystem Services …). A free': '摘要来自 Crossref、OpenAlex、Semantic Scholar 和 Europe PMC，这些都是免费的，但不包含大多数 Elsevier 期刊（Applied Geography、Landscape and Urban Planning、Ecosystem Services…）的摘要。一个免费的',
  'Change repository': '更换仓库', 'Use a different GitHub repository': '使用另一个 GitHub 仓库', 'GitHub repository': 'GitHub 仓库', 'Owner': '所有者', 'Repository': '仓库', 'Continue': '继续',
  'Which repository?': '哪个仓库？', 'This page is not on a <username>.github.io address, so the Site Manager cannot tell which GitHub repository holds the website. Enter it once; it is remembered in this browser.': '本页不在 <用户名>.github.io 地址下，站点管理无法判断网站所在的 GitHub 仓库。输入一次即可，本浏览器会记住。',
};
