// City icons for the footprint pages and the Site Manager.
// Each place gets an icon that matches its character: skyline for modern cities, Chinese heritage
// (Temple of Heaven, pagoda, city wall, water town …), landscapes (karst, mountains, lake, desert,
// grassland …) and world landmarks (cathedral, castle, windmill, torii …). The icon is chosen
// automatically from the city name, the country and the saved sights; `place.icon` overrides it.
// All icons share one style: 24×24, 1.8 px rounded strokes, currentColor.
(function () {
  const S = (inner, fill) => `<svg viewBox="0 0 24 24" fill="${fill || 'none'}" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${inner}</svg>`;
  const ICONS = {
    // ── generic ──
    city:       { en: 'City', zh: '城市', svg: S('<path d="M3 21h18"/><path d="M5 21V8l5-3v16"/><path d="M10 21V11h9v10"/><path d="M13 14h3M13 17h3M7 10v.01M7 13v.01M7 16v.01"/>') },
    lived:      { en: 'Home', zh: '居住地', svg: S('<path d="M3 11l9-7 9 7"/><path d="M5 10v10h14V10"/><path d="M10 20v-5h4v5"/>') },
    academic:   { en: 'Campus', zh: '学术', svg: S('<path d="M2 9l10-5 10 5-10 5z"/><path d="M6 11v5c3 2.5 9 2.5 12 0v-5"/><path d="M22 9v6"/>') },
    // ── modern ──
    skyline:    { en: 'Skyline', zh: '现代都市', svg: S('<path d="M2 21h20"/><path d="M4 21V12h4v9"/><path d="M8 21V6l4-2v17"/><path d="M12 21V9h4v12"/><path d="M16 21v-6h4v6"/><path d="M14 12h.01M14 15h.01M14 18h.01M6 15h.01M6 18h.01M10 8h.01M10 11h.01M10 14h.01M10 17h.01"/>') },
    tower:      { en: 'TV tower', zh: '电视塔', svg: S('<path d="M12 2v3"/><circle cx="12" cy="8" r="2.6"/><path d="M10.6 10.4L9 21M13.4 10.4L15 21"/><path d="M9.7 15.5h4.6"/><path d="M6 21h12"/><path d="M8.5 4.5a5 5 0 0 1 7 0"/>') },
    bridge:     { en: 'Bridge', zh: '大桥', svg: S('<path d="M2 15h20"/><path d="M6 15V7M18 15V7"/><path d="M2 12c3-6 6-6 10-6s7 0 10 6"/><path d="M9 15v-4M12 15v-6M15 15v-4"/><path d="M4 19h16"/>') },
    harbour:    { en: 'Harbour', zh: '港口', svg: S('<path d="M3 18c2 1.5 4 1.5 6 0s4-1.5 6 0 4 1.5 6 0"/><path d="M5 15l1-6h12l1 6"/><path d="M8 9V5h8v4"/><path d="M12 5V2"/><path d="M9 12h6"/>') },
    // ── Chinese heritage ──
    tiantan:    { en: 'Temple of Heaven', zh: '天坛', svg: S('<path d="M12 2v2"/><path d="M8.5 7.5c1-3.5 6-3.5 7 0"/><path d="M9.5 7.5v2.5h5V7.5"/><path d="M6.5 12.5c2-3.5 9-3.5 11 0"/><path d="M7.5 12.5v3h9v-3"/><path d="M4.5 18c3-3.5 12-3.5 15 0"/><path d="M5.5 18v3h13v-3"/><path d="M3 21h18"/>') },
    pagoda:     { en: 'Pagoda', zh: '古塔', svg: S('<path d="M12 2v2"/><path d="M8 7l4-3 4 3z"/><path d="M9 7v3M15 7v3"/><path d="M6.5 12.5L12 10l5.5 2.5"/><path d="M8 13v3M16 13v3"/><path d="M5 18l7-2.5 7 2.5"/><path d="M7 18.5V21M17 18.5V21"/><path d="M4 21h16"/>') },
    palace:     { en: 'Palace hall', zh: '宫殿', svg: S('<path d="M3 9c3-1 5-3 9-5 4 2 6 4 9 5"/><path d="M5 9v3h14V9"/><path d="M6 12v9M18 12v9"/><path d="M9 21v-5h6v5"/><path d="M2 21h20"/><path d="M12 4V2"/>') },
    citywall:   { en: 'City wall', zh: '城墙古都', svg: S('<path d="M2 21h20"/><path d="M4 21v-8h16v8"/><path d="M4 13V9h2v2h3V9h6v2h3V9h2v4"/><path d="M8 9c1-2 3-3.5 4-4.5 1 1 3 2.5 4 4.5"/><path d="M10 21v-5h4v5"/>') },
    greatwall:  { en: 'Great Wall', zh: '长城', svg: S('<path d="M2 15c3-2 4-8 7-8s4 6 7 6 4-6 6-6"/><path d="M2 19c3-2 4-8 7-8s4 6 7 6 4-6 6-6"/><path d="M2 15v4M22 7v4"/><path d="M8 7.5V5h2v2.5M15 12.5V10h2v2.5"/><path d="M4.5 12.5v-2M20 9.5v-2"/><path d="M3 21h18"/>') },
    garden:     { en: 'Classical garden', zh: '园林', svg: S('<circle cx="12" cy="12" r="9"/><path d="M8 12.5l4-3.5 4 3.5"/><path d="M9.5 12.5V17M14.5 12.5V17"/><path d="M8.5 17h7"/><path d="M12 9V7"/><path d="M5 19.5c1.5-1 3-1 4.5 0"/><path d="M3 21h18"/>') },
    watertown:  { en: 'Water town', zh: '水乡古镇', svg: S('<path d="M3 20c2 1 4 1 6 0s4-1 6 0 4 1 6 0"/><path d="M2 16c3-5 7-6 10-6s7 1 10 6"/><path d="M4 10V6l3-2 3 2v4"/><path d="M14 10V6l3-2 3 2v4"/><path d="M6.5 10v-2M17.5 10v-2"/>') },
    tibet:      { en: 'Tibetan palace', zh: '藏地', svg: S('<path d="M2 21h20"/><path d="M4 21v-5h16v5"/><path d="M6 16v-5h12v5"/><path d="M9 11V6h6v5"/><path d="M12 6V3"/><path d="M8 18h.01M11 18h.01M14 18h.01M17 18h.01M8 13.5h.01M11 13.5h.01M14 13.5h.01"/>') },
    karst:      { en: 'Karst landscape', zh: '山水喀斯特', svg: S('<path d="M2 19c2 .8 3 .8 5 0s3-.8 5 0 3 .8 5 0 3-.8 5 0"/><path d="M3 16c.3-3 1.2-7 3-9.5 1.8 2.5 2.7 6.5 3 9.5"/><path d="M9.5 16c.3-4 1.3-8.5 2.8-11.5 1.5 3 2.5 7.5 2.8 11.5"/><path d="M15.5 16c.3-2.5 1-5.5 2.2-7.5 1.2 2 1.9 5 2.2 7.5"/><path d="M5 12l1 .8 1-.8M11.3 9l1 .8 1-.8"/>') },
    mountain:   { en: 'Mountains', zh: '名山', svg: S('<path d="M2 20l6-11 4 6 2-3 8 8z"/><path d="M8 9l2 3"/><path d="M14 12l3-4.5 1.5 2.5"/>') },
    pillars:    { en: 'Stone pillars', zh: '石柱峰林', svg: S('<path d="M2 21h20"/><path d="M4 21V10l2-3 2 3v11"/><path d="M10 21V7l2-3 2 3v14"/><path d="M16 21v-9l2-3 2 3v9"/><path d="M5 14h2M11 12h2M17 16h2"/>') },
    snowmountain:{ en: 'Snow mountain', zh: '雪山', svg: S('<path d="M2 20l7-13 4 7 3-5 6 11z"/><path d="M6.5 11.5l1.5 1 1.5-1.5 1.5 1.5"/><path d="M14.5 12.5l1.5 1 1.5-1.5"/>', 'none') },
    lake:       { en: 'Lake', zh: '湖泊', svg: S('<path d="M3 13l5-6 4 5 3-3 6 4"/><path d="M2 17c2 1 4 1 6 0s4-1 6 0 4 1 6 0"/><path d="M4 20.5c2 1 4 1 6 0s4-1 6 0 4 1 4 0"/>') },
    waterfall:  { en: 'Waterfall', zh: '瀑布', svg: S('<path d="M3 4v7M21 4v7"/><path d="M3 4h4v2M21 4h-4v2"/><path d="M8.5 6c.8 4 .8 8-.5 13M12 6c.8 4 .8 8-.5 13M15.5 6c.8 4 .8 8-.5 13"/><path d="M3 20c2 1 4 1 6 0s4-1 6 0 4 1 6 0"/><path d="M7 6h10"/>') },
    canyon:     { en: 'Canyon', zh: '峡谷', svg: S('<path d="M2 4v16"/><path d="M22 4v16"/><path d="M2 6h4l2 4 1 6-2 4"/><path d="M22 6h-4l-2 4-1 6 2 4"/><path d="M9 21c1 .6 2 .6 3 0s2-.6 3 0"/>') },
    camel:      { en: 'Desert', zh: '沙漠', svg: S('<path d="M3 20c3-1.5 6-1.5 9 0s6 1.5 9 0"/><path d="M5 16v-3c0-2 1.5-4 3.5-4s2 1 3.5 1 1.5-1.5 3.5-1.5S19 10 19 12v4"/><path d="M19 12c1-1 1.5-3 1.5-5"/><path d="M20.5 7h1.5l1 1.5"/><path d="M7 16v3M10 16v3M14 16v3M17 16v3"/>') },
    yurt:       { en: 'Grassland', zh: '草原', svg: S('<path d="M3 20h18"/><path d="M5 20v-6h14v6"/><path d="M4 14c2-5 5-7 8-7s6 2 8 7"/><path d="M12 7V5"/><path d="M11 20v-4h2v4"/><path d="M2 17l1-1 1 1M20 17l1-1 1 1"/>') },
    beach:      { en: 'Beach', zh: '海滩', svg: S('<path d="M3 20.5c2 1 4 1 6 0s4-1 6 0 4 1 6 0"/><path d="M9 20.5c0-6 1-10 3-13"/><path d="M12 7.5c-3-1.5-6-.5-7.5 2 2.5-.5 5-.5 7.5-2z"/><path d="M12 7.5c3-1.5 6-.5 7.5 2-2.5-.5-5-.5-7.5-2z"/><path d="M12 7.5c-1-3 0-5 2-6-.3 2.5 0 4-2 6z"/><path d="M12 7.5c2-2.5 4-3 6-2.5-2 .5-4 1.5-6 2.5z"/><circle cx="19" cy="14.5" r="2"/>') },
    island:     { en: 'Island', zh: '海岛', svg: S('<path d="M2 20c2 1 4 1 6 0s4-1 6 0 4 1 6 0"/><path d="M4 18c1-4 4-7 8-7s7 3 8 7"/><path d="M12 11V6"/><path d="M12 6c-2.5-1.5-5-1-6.5 1 2.2-.2 4.2 0 6.5-1z"/><path d="M12 6c2.5-1.5 5-1 6.5 1-2.2-.2-4.2 0-6.5-1z"/><path d="M12 6c-.5-2.5.5-4 2.5-5-.5 1.8-.5 3.5-2.5 5z"/><circle cx="19" cy="4" r="1.6"/>') },
    panda:      { en: 'Panda', zh: '熊猫', svg: S('<circle cx="12" cy="13" r="7"/><circle cx="7" cy="7" r="2.3" fill="currentColor"/><circle cx="17" cy="7" r="2.3" fill="currentColor"/><ellipse cx="9.5" cy="12" rx="1.8" ry="2.2" fill="currentColor"/><ellipse cx="14.5" cy="12" rx="1.8" ry="2.2" fill="currentColor"/><path d="M11 16h2l-1 1.2z" fill="currentColor"/>') },
    forest:     { en: 'Forest', zh: '森林', svg: S('<path d="M8 21v-3M16 21v-3"/><path d="M8 18H3l2.5-4H4l2.5-4H5.5L8 5l2.5 5H9l2.5 4H10l3 4z"/><path d="M16 18h5l-2.5-4H20l-2.5-4h1L16 6l-2.2 4"/>') },
    volcano:    { en: 'Volcano', zh: '火山', svg: S('<path d="M3 21l5-12h8l5 12z"/><path d="M8 9c1-2 1.5-4 1-6"/><path d="M12 9c.5-2 .5-4 0-6"/><path d="M16 9c-1-2-1.5-4-1-6"/><path d="M9 15l2-2 2 3 2-2"/>') },
    // ── world landmarks ──
    cathedral:  { en: 'Cathedral', zh: '哥特教堂', svg: S('<path d="M3 21h18"/><path d="M5 21V12l2-5 2 5v9"/><path d="M15 21V12l2-5 2 5v9"/><path d="M9 21v-7h6v7"/><path d="M12 14V9"/><path d="M12 9l-2 2M12 9l2 2"/><path d="M7 7V4M17 7V4"/><path d="M11.5 18h1"/>') },
    castle:     { en: 'Castle', zh: '城堡', svg: S('<path d="M3 21h18"/><path d="M4 21V9h4v12"/><path d="M16 21V9h4v12"/><path d="M8 21v-9h8v9"/><path d="M4 9V6h1v2h2V6h1v3M16 9V6h1v2h2V6h1v3"/><path d="M11 21v-4h2v4"/><path d="M10 9l2-4 2 4"/>') },
    oldtown:    { en: 'Old town', zh: '欧洲老城', svg: S('<path d="M2 21h20"/><path d="M3 21V9l3-3 3 3v12"/><path d="M9 21V7l3.5-3 3.5 3v14"/><path d="M16 21V10l3-3 2.5 3v11"/><path d="M5.5 13h.01M5.5 17h.01M12.5 11h.01M12.5 15h.01M12.5 19h.01M19 14h.01M19 18h.01"/>') },
    windmill:   { en: 'Windmill', zh: '风车', svg: S('<path d="M9 21l1.5-10h3L15 21z"/><path d="M7 21h10"/><path d="M12 11l-5-5M12 11l5-5M12 11l-5 4M12 11l5 4"/><circle cx="12" cy="11" r="1.2" fill="currentColor"/>') },
    classical:  { en: 'Classical temple', zh: '古希腊罗马', svg: S('<path d="M3 21h18"/><path d="M4 9l8-5 8 5z"/><path d="M5 9v2h14V9"/><path d="M6 11v8M10 11v8M14 11v8M18 11v8"/><path d="M4 19h16"/>') },
    dome:       { en: 'Dome', zh: '穹顶', svg: S('<path d="M3 21h18"/><path d="M5 21v-8h14v8"/><path d="M6 13c0-5 3-7 6-7s6 2 6 7"/><path d="M12 6V3"/><path d="M11 3h2"/><path d="M8 13v8M16 13v8"/><path d="M11 21v-4h2v4"/>') },
    eiffel:     { en: 'Eiffel Tower', zh: '埃菲尔铁塔', svg: S('<path d="M12 2v2"/><path d="M10.5 4h3l1 7h-5z"/><path d="M9.5 11c-.5 4-2.5 7-5.5 10h5c1-2 2-3 3-3s2 1 3 3h5c-3-3-5-6-5.5-10"/><path d="M7 17h10"/><path d="M8.5 11h7"/>') },
    bigben:     { en: 'Clock tower', zh: '钟楼', svg: S('<path d="M12 2l3 3v3H9V5z"/><path d="M9 8h6v13H9z"/><circle cx="12" cy="12" r="2"/><path d="M12 12v-1.2M12 12h.9"/><path d="M10.5 17h3M10.5 19h3"/><path d="M6 21h12"/>') },
    oniondome:  { en: 'Onion domes', zh: '洋葱穹顶', svg: S('<path d="M3 21h18"/><path d="M5 21v-7h4v7M15 21v-7h4v7M9 21V11h6v10"/><path d="M5 14c0-3 1-4 2-6 1 2 2 3 2 6"/><path d="M15 14c0-3 1-4 2-6 1 2 2 3 2 6"/><path d="M9 11c0-4 1.5-6 3-8 1.5 2 3 4 3 8"/><path d="M12 3V1.5M7 8V6.5M17 8V6.5"/>') },
    colosseum:  { en: 'Amphitheatre', zh: '古罗马竞技场', svg: S('<path d="M3 20h18"/><path d="M4 20V9c2-1.5 4-2 8-2s6 .5 8 2v11"/><path d="M4 13c2-1 4-1.5 8-1.5s6 .5 8 1.5"/><path d="M4 16.5c2-1 4-1.5 8-1.5s6 .5 8 1.5"/><path d="M7 20v-3M11 20v-3.5M15 20v-3.5M19 20v-3M7 12.5v-3M11 12v-3M15 12v-3"/>') },
    lighthouse: { en: 'Lighthouse', zh: '灯塔海岸', svg: S('<path d="M10 21l1-12h2l1 12z"/><path d="M9 9h6l-1-3H10z"/><path d="M11 6V4h2v2"/><path d="M4 6l3 1M20 6l-3 1"/><path d="M3 21c2 1 4 1 6 0M15 21c2 1 4 1 6 0"/>') },
    mosque:     { en: 'Mosque', zh: '清真寺', svg: S('<path d="M3 21h18"/><path d="M6 21v-7h12v7"/><path d="M7 14c0-4 2.5-6 5-7 2.5 1 5 3 5 7"/><path d="M12 7V4"/><path d="M4 21V8l1-2 1 2v13M18 21V8l1-2 1 2v13"/><path d="M11 21v-4h2v4"/>') },
    pyramid:    { en: 'Pyramids', zh: '金字塔', svg: S('<path d="M2 19l8-12 6 12z"/><path d="M10 7l4 12"/><path d="M14 19l4-7 4 7z"/><path d="M18 12l1.5 7"/><circle cx="19" cy="5" r="1.8"/>') },
    torii:      { en: 'Torii', zh: '鸟居', svg: S('<path d="M3 6c3-1 15-1 18 0"/><path d="M5 10h14"/><path d="M7 6v15M17 6v15"/><path d="M12 6v4"/><path d="M5 21h4M15 21h4"/>') },
    hanok:      { en: 'Palace gate', zh: '韩式殿门', svg: S('<path d="M2 9c3-1 6-3 10-4 4 1 7 3 10 4"/><path d="M4 9v2h16V9"/><path d="M5 11v10M19 11v10"/><path d="M8 21v-6h8v6"/><path d="M12 15v6"/><path d="M3 21h18"/><path d="M3 15c2-.8 4-2 6-2M21 15c-2-.8-4-2-6-2"/>') },
    stupa:      { en: 'Stupa', zh: '佛塔', svg: S('<path d="M12 2v3"/><path d="M11 5h2l1 4h-4z"/><path d="M8 9h8l2 5H6z"/><path d="M5 14h14v3H5z"/><path d="M4 17h16v4H4z"/><path d="M10 21v-2h4v2"/>') },
    liberty:    { en: 'Statue', zh: '雕像', svg: S('<circle cx="12" cy="7.5" r="2.2"/><path d="M9.5 5.5L8.5 4M12 5V3M14.5 5.5l1-1.5"/><path d="M12 10v3"/><path d="M12 10l3.5-3"/><path d="M15.5 7V3.5"/><circle cx="15.5" cy="2.3" r="0.9" fill="currentColor"/><path d="M12 11l-3 1.5v2h2"/><path d="M8.5 21l1-8h5l1 8z"/><path d="M6 21h12"/>') },
    opera:      { en: 'Opera house', zh: '歌剧院', svg: S('<path d="M2 20h20"/><path d="M3 20c0-4 3-7 6-9-1 3-1 6 0 9"/><path d="M8 20c0-5 3-9 6-11-1 4-1 7 0 11"/><path d="M13 20c0-4 2.5-7 5-8-1 3-1 5 0 8"/><path d="M17 20c0-3 1.5-5 3-6-.5 2-.5 4 0 6"/>') },
    savanna:    { en: 'Savanna', zh: '草原原野', svg: S('<path d="M2 21h20"/><path d="M12 21v-9"/><path d="M4 11c2-4 6-6 8-6s6 2 8 6c-3-1-6-1-8-1s-5 0-8 1z"/><path d="M12 12l-4-3M12 12l4-3"/><circle cx="19" cy="4" r="1.8"/>') },
    jungle:     { en: 'Rainforest', zh: '雨林', svg: S('<path d="M12 21V11"/><path d="M12 11c-4-1-6-4-6-8 3 1 5 3 6 8z"/><path d="M12 11c4-1 6-4 6-8-3 1-5 3-6 8z"/><path d="M12 15c-3 0-5-1.5-6-4 3 0 5 1 6 4z"/><path d="M12 15c3 0 5-1.5 6-4-3 0-5 1-6 4z"/><path d="M6 21h12"/>') },
    // ── experiences ──
    hotspring:  { en: 'Hot spring', zh: '温泉', svg: S('<path d="M4 15c0 3 3.5 5 8 5s8-2 8-5-3.5-5-8-5-8 2-8 5z"/><path d="M8 7c-1-1.5 1-2.5 0-4M12 7c-1-1.5 1-2.5 0-4M16 7c-1-1.5 1-2.5 0-4"/><path d="M8 15c1 1 2.5 1.5 4 1.5s3-.5 4-1.5"/>') },
    ski:        { en: 'Ski resort', zh: '滑雪', svg: S('<path d="M2 20l7-13 4 7 3-5 6 11z"/><path d="M8.5 9.5l1.5 1.5 1.5-1.5"/><path d="M3 22l16-5"/><circle cx="17" cy="4" r="1.5"/>') },
  };
  const KEYS = Object.keys(ICONS);

  // ── Automatic choice ──
  // Specific cities (English name, lower case, or Chinese name) → icon
  const CITY = {
    // China: ancient capitals and heritage cities
    beijing: 'tiantan', 北京: 'tiantan', "xi'an": 'citywall', xian: 'citywall', 西安: 'citywall', nanjing: 'citywall', 南京: 'citywall', pingyao: 'citywall', 平遥: 'citywall', datong: 'citywall', 大同: 'citywall',
    luoyang: 'pagoda', 洛阳: 'pagoda', kaifeng: 'pagoda', 开封: 'pagoda', hangzhou: 'pagoda', 杭州: 'pagoda', anyang: 'pagoda', 安阳: 'pagoda', zhengzhou: 'pagoda', 郑州: 'pagoda', dengfeng: 'pagoda', 登封: 'pagoda', yangzhou: 'pagoda', 扬州: 'pagoda', shaoxing: 'watertown', 绍兴: 'watertown',
    suzhou: 'garden', 苏州: 'garden', wuxi: 'garden', 无锡: 'garden', wuzhen: 'watertown', 乌镇: 'watertown', zhouzhuang: 'watertown', 周庄: 'watertown', tongli: 'watertown', 同里: 'watertown', xitang: 'watertown', 西塘: 'watertown', jiaxing: 'watertown', 嘉兴: 'watertown', huzhou: 'watertown', 湖州: 'watertown',
    shenyang: 'palace', 沈阳: 'palace', chengde: 'palace', 承德: 'palace', qufu: 'palace', 曲阜: 'palace', jinan: 'lake', 济南: 'lake', lijiang: 'snowmountain', 丽江: 'snowmountain', dali: 'lake', 大理: 'lake', shangri: 'tibet', 香格里拉: 'tibet', 迪庆: 'tibet',
    lhasa: 'tibet', 拉萨: 'tibet', shigatse: 'tibet', 日喀则: 'tibet', xining: 'tibet', 西宁: 'tibet', yushu: 'tibet', 玉树: 'tibet', 果洛: 'tibet', 甘孜: 'tibet', 阿坝: 'tibet', 黄南: 'tibet', 甘南: 'tibet', nyingchi: 'snowmountain', 林芝: 'snowmountain',
    guilin: 'karst', 桂林: 'karst', yangshuo: 'karst', 阳朔: 'karst', wulong: 'karst', 武隆: 'karst', libo: 'karst', 荔波: 'karst', 黔南: 'karst', shilin: 'karst', 石林: 'karst', 兴义: 'karst', 黔西南: 'karst', 贺州: 'karst', 柳州: 'karst',
    zhangjiajie: 'pillars', 张家界: 'pillars', 武陵源: 'pillars', 恩施: 'canyon', enshi: 'canyon', huangshan: 'mountain', 黄山: 'mountain', 泰安: 'mountain', 'tai\'an': 'mountain', taian: 'mountain', emeishan: 'mountain', 峨眉山: 'mountain', 乐山: 'mountain', leshan: 'mountain', 九江: 'mountain', jiujiang: 'mountain', 华阴: 'mountain', 武夷山: 'mountain', wuyishan: 'mountain', 衡阳: 'mountain', 三清山: 'mountain', 上饶: 'mountain', 雁荡: 'mountain', 五台山: 'pagoda', 忻州: 'pagoda',
    dunhuang: 'camel', 敦煌: 'camel', jiuquan: 'camel', 酒泉: 'camel', 嘉峪关: 'greatwall', jiayuguan: 'greatwall', 张掖: 'canyon', zhangye: 'canyon', turpan: 'camel', 吐鲁番: 'camel', kashgar: 'mosque', 喀什: 'mosque', 和田: 'camel', 阿克苏: 'camel', urumqi: 'snowmountain', 乌鲁木齐: 'snowmountain', 伊犁: 'yurt', 伊宁: 'yurt', 那拉提: 'yurt', 阿勒泰: 'snowmountain', 喀纳斯: 'lake', 博乐: 'lake', 巴音郭楞: 'yurt', 库尔勒: 'camel', 银川: 'camel', yinchuan: 'camel', 中卫: 'camel',
    hohhot: 'yurt', 呼和浩特: 'yurt', 锡林郭勒: 'yurt', 锡林浩特: 'yurt', 呼伦贝尔: 'yurt', hulunbuir: 'yurt', 海拉尔: 'yurt', 鄂尔多斯: 'camel', 阿拉善: 'camel', 包头: 'yurt', 赤峰: 'yurt', 乌兰察布: 'yurt', 张北: 'yurt', 承德坝上: 'yurt',
    sanya: 'beach', 三亚: 'beach', haikou: 'beach', 海口: 'beach', 万宁: 'beach', 陵水: 'beach', xiamen: 'island', 厦门: 'island', 北海: 'beach', beihai: 'beach', 舟山: 'island', zhoushan: 'island', 青岛: 'harbour', qingdao: 'harbour', 大连: 'harbour', dalian: 'harbour', 烟台: 'lighthouse', 威海: 'lighthouse', 秦皇岛: 'greatwall', 北戴河: 'beach', 珠海: 'island', zhuhai: 'island', 汕头: 'harbour', 湛江: 'harbour', 宁波: 'harbour', ningbo: 'harbour', 天津: 'harbour', tianjin: 'harbour',
    shanghai: 'tower', 上海: 'tower', guangzhou: 'tower', 广州: 'tower', shenzhen: 'skyline', 深圳: 'skyline', 'hong kong': 'skyline', 香港: 'skyline', hongkong: 'skyline', macau: 'dome', macao: 'dome', 澳门: 'dome', chongqing: 'skyline', 重庆: 'skyline', wuhan: 'pagoda', 武汉: 'pagoda', changsha: 'skyline', 长沙: 'skyline', 岳阳: 'lake', yueyang: 'lake',
    chengdu: 'panda', 成都: 'panda', 都江堰: 'panda', 雅安: 'panda', 卧龙: 'panda', 九寨沟: 'lake', 阿坝州: 'lake', jiuzhaigou: 'lake', 康定: 'snowmountain', 稻城: 'snowmountain', kunming: 'lake', 昆明: 'lake', 西双版纳: 'jungle', 景洪: 'jungle', xishuangbanna: 'jungle', 腾冲: 'volcano', tengchong: 'volcano', 普洱: 'jungle', 贵阳: 'karst', guiyang: 'karst', 安顺: 'waterfall', anshun: 'waterfall', 黄果树: 'waterfall',
    harbin: 'oniondome', 哈尔滨: 'oniondome', 漠河: 'forest', 伊春: 'forest', 长白山: 'lake', 延吉: 'hanok', 延边: 'hanok', 吉林: 'forest', 长春: 'skyline', changchun: 'skyline', 牡丹江: 'lake', 大兴安岭: 'forest', 阿尔山: 'forest', 雪乡: 'ski', 亚布力: 'ski', 崇礼: 'ski',
    taipei: 'tower', 台北: 'tower', 花莲: 'canyon', hualien: 'canyon', 日月潭: 'lake', 南投: 'lake', 台南: 'palace', tainan: 'palace', 高雄: 'harbour', kaohsiung: 'harbour', 台中: 'skyline', 垦丁: 'beach',
    fuzhou: 'palace', 福州: 'palace', 泉州: 'mosque', quanzhou: 'mosque', 南靖: 'watertown', 永定: 'watertown', 龙岩: 'watertown', 婺源: 'watertown', 景德镇: 'palace', 南昌: 'pagoda', 黄山市: 'watertown', 屯溪: 'watertown', 徽州: 'watertown', 宏村: 'watertown', 西递: 'watertown', 凤凰: 'watertown', 湘西: 'watertown', 镇远: 'watertown', 阆中: 'citywall', 荆州: 'citywall', 襄阳: 'citywall', 兴城: 'citywall', 寿县: 'citywall',
    // Europe
    paris: 'eiffel', 巴黎: 'eiffel', london: 'bigben', 伦敦: 'bigben', rome: 'colosseum', roma: 'colosseum', 罗马: 'colosseum', athens: 'classical', 雅典: 'classical', 'vatican city': 'dome', vatican: 'dome', 梵蒂冈: 'dome', florence: 'dome', firenze: 'dome', 佛罗伦萨: 'dome', venice: 'watertown', venezia: 'watertown', 威尼斯: 'watertown', milan: 'cathedral', milano: 'cathedral', 米兰: 'cathedral', pisa: 'tower', naples: 'volcano', napoli: 'volcano', 那不勒斯: 'volcano', catania: 'volcano',
    amsterdam: 'oldtown', 阿姆斯特丹: 'oldtown', kinderdijk: 'windmill', zaandam: 'windmill', 'zaanse schans': 'windmill', rotterdam: 'skyline', 鹿特丹: 'skyline', 'the hague': 'oldtown', 'den haag': 'oldtown', 海牙: 'oldtown', groningen: 'bigben', 格罗宁根: 'bigben', utrecht: 'bigben', 乌得勒支: 'bigben', delft: 'oldtown', leiden: 'windmill', 莱顿: 'windmill', giethoorn: 'watertown', 羊角村: 'watertown', maastricht: 'oldtown', texel: 'lighthouse',
    barcelona: 'cathedral', 巴塞罗那: 'cathedral', madrid: 'palace', 马德里: 'dome', seville: 'cathedral', sevilla: 'cathedral', 塞维利亚: 'cathedral', granada: 'mosque', 格拉纳达: 'mosque', lisbon: 'oldtown', lisboa: 'oldtown', 里斯本: 'oldtown', porto: 'bridge', 波尔图: 'bridge',
    berlin: 'classical', 柏林: 'classical', munich: 'cathedral', münchen: 'cathedral', 慕尼黑: 'cathedral', cologne: 'cathedral', köln: 'cathedral', 科隆: 'cathedral', hamburg: 'harbour', 汉堡: 'harbour', frankfurt: 'skyline', 法兰克福: 'skyline', heidelberg: 'castle', 海德堡: 'castle', neuschwanstein: 'castle', füssen: 'castle', dresden: 'dome', 德累斯顿: 'dome', nuremberg: 'castle', 纽伦堡: 'castle',
    vienna: 'dome', wien: 'dome', 维也纳: 'dome', salzburg: 'castle', 萨尔茨堡: 'castle', innsbruck: 'snowmountain', hallstatt: 'lake', 哈尔施塔特: 'lake', prague: 'castle', praha: 'castle', 布拉格: 'castle', budapest: 'dome', 布达佩斯: 'dome', bratislava: 'castle', krakow: 'castle', kraków: 'castle', 克拉科夫: 'castle', warsaw: 'oldtown', 华沙: 'oldtown',
    zurich: 'lake', zürich: 'lake', 苏黎世: 'lake', geneva: 'lake', genève: 'lake', 日内瓦: 'lake', lucerne: 'bridge', luzern: 'bridge', 卢塞恩: 'bridge', interlaken: 'snowmountain', 因特拉肯: 'snowmountain', zermatt: 'snowmountain', 采尔马特: 'snowmountain', grindelwald: 'snowmountain', chamonix: 'snowmountain', 夏慕尼: 'snowmountain', bern: 'oldtown', 伯尔尼: 'oldtown',
    brussels: 'oldtown', bruxelles: 'oldtown', 布鲁塞尔: 'oldtown', bruges: 'watertown', brugge: 'watertown', 布鲁日: 'watertown', ghent: 'castle', gent: 'castle', antwerp: 'cathedral', antwerpen: 'cathedral', luxembourg: 'castle',
    copenhagen: 'harbour', københavn: 'harbour', 哥本哈根: 'harbour', stockholm: 'harbour', 斯德哥尔摩: 'harbour', oslo: 'harbour', 奥斯陆: 'opera', bergen: 'harbour', 卑尔根: 'harbour', tromsø: 'snowmountain', tromso: 'snowmountain', helsinki: 'dome', 赫尔辛基: 'dome', rovaniemi: 'ski', reykjavik: 'volcano', reykjavík: 'volcano', 雷克雅未克: 'volcano', tallinn: 'oldtown', riga: 'oldtown', vilnius: 'oldtown',
    edinburgh: 'castle', 爱丁堡: 'castle', oxford: 'academic', 牛津: 'academic', cambridge: 'academic', 剑桥: 'academic', bath: 'classical', york: 'cathedral', liverpool: 'harbour', manchester: 'skyline', dublin: 'oldtown', 都柏林: 'oldtown', glasgow: 'cathedral',
    moscow: 'oniondome', 莫斯科: 'oniondome', 'saint petersburg': 'oniondome', 'st petersburg': 'oniondome', 圣彼得堡: 'oniondome', kyiv: 'oniondome', kiev: 'oniondome', 基辅: 'oniondome', istanbul: 'mosque', 伊斯坦布尔: 'mosque', cappadocia: 'canyon', göreme: 'canyon', 卡帕多奇亚: 'canyon', antalya: 'beach', dubrovnik: 'castle', 杜布罗夫尼克: 'castle', split: 'classical', santorini: 'island', 圣托里尼: 'island', mykonos: 'windmill', nice: 'beach', 尼斯: 'beach', marseille: 'harbour', lyon: 'cathedral', 里昂: 'cathedral', 'mont saint-michel': 'castle', strasbourg: 'cathedral', 斯特拉斯堡: 'cathedral', bordeaux: 'oldtown', 'edinburgh of the seven seas': 'island',
    // Americas, Oceania, Asia, Africa
    'new york': 'liberty', 'new york city': 'liberty', 纽约: 'liberty', 'san francisco': 'bridge', 旧金山: 'bridge', 'los angeles': 'beach', 洛杉矶: 'beach', chicago: 'skyline', 芝加哥: 'skyline', 'washington': 'dome', 'washington, d.c.': 'dome', 华盛顿: 'dome', boston: 'academic', 波士顿: 'academic', seattle: 'tower', 西雅图: 'tower', 'las vegas': 'skyline', miami: 'beach', 迈阿密: 'beach', honolulu: 'beach', 檀香山: 'beach', 'niagara falls': 'waterfall', 尼亚加拉: 'waterfall', denver: 'mountain', 'salt lake city': 'mountain', anchorage: 'snowmountain',
    toronto: 'tower', 多伦多: 'tower', vancouver: 'harbour', 温哥华: 'harbour', montreal: 'cathedral', montréal: 'cathedral', 蒙特利尔: 'cathedral', banff: 'lake', 班夫: 'lake', 'quebec city': 'castle', québec: 'castle', ottawa: 'bigben', 渥太华: 'bigben',
    'mexico city': 'pyramid', 墨西哥城: 'pyramid', cancún: 'beach', cancun: 'beach', 坎昆: 'beach', 'rio de janeiro': 'liberty', 里约热内卢: 'liberty', 'são paulo': 'skyline', 'buenos aires': 'oldtown', 布宜诺斯艾利斯: 'oldtown', lima: 'oldtown', 利马: 'oldtown', cusco: 'mountain', 库斯科: 'mountain', 'machu picchu': 'mountain', santiago: 'snowmountain', 圣地亚哥: 'snowmountain', bogotá: 'mountain', havana: 'oldtown', 哈瓦那: 'oldtown',
    sydney: 'opera', 悉尼: 'opera', melbourne: 'skyline', 墨尔本: 'skyline', cairns: 'jungle', 'gold coast': 'beach', 黄金海岸: 'beach', brisbane: 'skyline', perth: 'beach', auckland: 'volcano', 奥克兰: 'volcano', queenstown: 'snowmountain', 皇后镇: 'snowmountain', wellington: 'harbour', 惠灵顿: 'harbour', rotorua: 'hotspring', christchurch: 'cathedral',
    tokyo: 'tower', 东京: 'tower', kyoto: 'torii', 京都: 'torii', nara: 'torii', 奈良: 'torii', osaka: 'castle', 大阪: 'castle', nikko: 'torii', 日光: 'torii', kamakura: 'torii', 镰仓: 'torii', hiroshima: 'torii', 广岛: 'torii', nagoya: 'castle', 名古屋: 'castle', hakone: 'hotspring', 箱根: 'hotspring', beppu: 'hotspring', 别府: 'hotspring', sapporo: 'ski', 札幌: 'ski', okinawa: 'beach', 冲绳: 'beach', naha: 'beach', fujiyoshida: 'volcano', 富士: 'volcano', 'mount fuji': 'volcano', kanazawa: 'garden', 金泽: 'garden', himeji: 'castle', 姬路: 'castle', fukuoka: 'skyline', yokohama: 'harbour', 横滨: 'harbour', 高山: 'oldtown', takayama: 'oldtown', 白川乡: 'oldtown', shirakawa: 'oldtown',
    seoul: 'hanok', 首尔: 'hanok', busan: 'harbour', 釜山: 'harbour', gyeongju: 'stupa', 庆州: 'stupa', jeju: 'volcano', 济州: 'volcano', incheon: 'harbour', 仁川: 'harbour',
    bangkok: 'stupa', 曼谷: 'stupa', 'chiang mai': 'stupa', 清迈: 'stupa', phuket: 'beach', 普吉: 'beach', ayutthaya: 'stupa', 大城: 'stupa', 'siem reap': 'stupa', 暹粒: 'stupa', 'angkor': 'stupa', 吴哥: 'stupa', 'luang prabang': 'stupa', 琅勃拉邦: 'stupa', hanoi: 'lake', 河内: 'lake', 'ho chi minh city': 'skyline', 胡志明市: 'skyline', 'ha long': 'karst', 'hạ long': 'karst', 下龙湾: 'karst', 'da nang': 'beach', 岘港: 'beach', 'hoi an': 'watertown', 会安: 'watertown', yangon: 'stupa', 仰光: 'stupa', bagan: 'stupa', 蒲甘: 'stupa', kathmandu: 'stupa', 加德满都: 'stupa', pokhara: 'snowmountain', 博卡拉: 'snowmountain', thimphu: 'tibet', 廷布: 'tibet', paro: 'tibet',
    singapore: 'skyline', 新加坡: 'skyline', 'kuala lumpur': 'skyline', 吉隆坡: 'skyline', bali: 'stupa', 巴厘岛: 'stupa', denpasar: 'beach', ubud: 'jungle', jakarta: 'skyline', manila: 'skyline', 马尼拉: 'skyline', boracay: 'beach', 长滩岛: 'beach', cebu: 'beach', 'kota kinabalu': 'mountain', 'borneo': 'jungle',
    delhi: 'mosque', 'new delhi': 'mosque', 新德里: 'mosque', 德里: 'mosque', agra: 'dome', 阿格拉: 'dome', jaipur: 'palace', 斋浦尔: 'palace', mumbai: 'skyline', 孟买: 'skyline', varanasi: 'stupa', 瓦拉纳西: 'stupa', goa: 'beach', 果阿: 'beach', colombo: 'stupa', 科伦坡: 'stupa', kandy: 'stupa', 'male': 'island', malé: 'island', 马累: 'island', maldives: 'island', 马尔代夫: 'island', karachi: 'skyline', lahore: 'mosque', 拉合尔: 'mosque', islamabad: 'mosque', dhaka: 'mosque', 达卡: 'mosque',
    dubai: 'skyline', 迪拜: 'skyline', 'abu dhabi': 'mosque', 阿布扎比: 'mosque', doha: 'skyline', 多哈: 'skyline', riyadh: 'skyline', 利雅得: 'skyline', mecca: 'mosque', makkah: 'mosque', 麦加: 'mosque', medina: 'mosque', jerusalem: 'dome', 耶路撒冷: 'dome', 'tel aviv': 'beach', 特拉维夫: 'beach', amman: 'classical', 安曼: 'classical', petra: 'canyon', 佩特拉: 'canyon', tehran: 'mosque', 德黑兰: 'mosque', isfahan: 'mosque', 伊斯法罕: 'mosque', shiraz: 'mosque', 设拉子: 'mosque', samarkand: 'mosque', 撒马尔罕: 'mosque', bukhara: 'mosque', 布哈拉: 'mosque', tashkent: 'mosque', 塔什干: 'mosque', almaty: 'snowmountain', 阿拉木图: 'snowmountain', astana: 'skyline', 阿斯塔纳: 'skyline', bishkek: 'snowmountain', 比什凯克: 'snowmountain', 'ulaanbaatar': 'yurt', 乌兰巴托: 'yurt', baku: 'skyline', 巴库: 'skyline', tbilisi: 'oldtown', 第比利斯: 'oldtown', yerevan: 'snowmountain',
    cairo: 'pyramid', 开罗: 'pyramid', giza: 'pyramid', luxor: 'classical', 卢克索: 'classical', aswan: 'camel', marrakesh: 'mosque', marrakech: 'mosque', 马拉喀什: 'mosque', casablanca: 'mosque', 卡萨布兰卡: 'mosque', fez: 'mosque', fès: 'mosque', 非斯: 'mosque', chefchaouen: 'oldtown', tunis: 'mosque', 突尼斯: 'mosque', nairobi: 'savanna', 内罗毕: 'savanna', 'masai mara': 'savanna', arusha: 'savanna', 阿鲁沙: 'savanna', serengeti: 'savanna', zanzibar: 'beach', 桑给巴尔: 'beach', 'cape town': 'mountain', 开普敦: 'mountain', johannesburg: 'skyline', 约翰内斯堡: 'skyline', 'victoria falls': 'waterfall', 维多利亚瀑布: 'waterfall', 'addis ababa': 'savanna', 亚的斯亚贝巴: 'savanna', kigali: 'jungle', kampala: 'savanna', lagos: 'skyline', accra: 'beach', dakar: 'beach', windhoek: 'camel', 'walvis bay': 'camel', sossusvlei: 'camel',
  };
  // Countries → default icon when the city is not in the table
  const EUROPE = 'AL AD AT BA BE BG BY CH CY CZ DE DK EE ES FI FO FR GB GG GI GR HR HU IE IM IS IT JE LI LT LU LV MC MD ME MK MT NL NO PL PT RO RS RU SE SI SK SM UA VA XK'.split(' ');
  const COUNTRY = { NL: 'windmill', GB: 'oldtown', IE: 'oldtown', FR: 'cathedral', IT: 'dome', ES: 'cathedral', PT: 'oldtown', DE: 'castle', AT: 'castle', CH: 'snowmountain', CZ: 'castle', SK: 'castle', HU: 'dome', PL: 'oldtown', GR: 'classical', CY: 'classical', RU: 'oniondome', UA: 'oniondome', BY: 'oniondome', TR: 'mosque',
    NO: 'snowmountain', SE: 'oldtown', FI: 'forest', DK: 'harbour', IS: 'volcano', EE: 'oldtown', LV: 'oldtown', LT: 'oldtown', HR: 'castle', SI: 'lake', RS: 'oniondome', BG: 'oniondome', RO: 'castle', BA: 'bridge', ME: 'castle', MK: 'oniondome', AL: 'castle', MT: 'dome', BE: 'oldtown', LU: 'castle', MC: 'harbour',
    US: 'skyline', CA: 'skyline', AU: 'skyline', NZ: 'snowmountain', SG: 'skyline', AE: 'skyline', QA: 'skyline', KW: 'skyline', BH: 'skyline', SA: 'mosque', OM: 'mosque', JO: 'classical', IL: 'dome', LB: 'dome', IR: 'mosque', IQ: 'mosque', UZ: 'mosque', KZ: 'yurt', KG: 'yurt', TJ: 'snowmountain', TM: 'camel', AF: 'mountain', PK: 'mosque', MN: 'yurt', AZ: 'skyline', GE: 'oldtown', AM: 'snowmountain',
    JP: 'torii', KR: 'hanok', KP: 'hanok', TH: 'stupa', LA: 'stupa', KH: 'stupa', MM: 'stupa', VN: 'watertown', MY: 'skyline', ID: 'volcano', PH: 'beach', BN: 'mosque', TL: 'beach', IN: 'dome', LK: 'stupa', NP: 'stupa', BT: 'tibet', BD: 'mosque', MV: 'island',
    EG: 'pyramid', MA: 'mosque', TN: 'mosque', DZ: 'mosque', LY: 'mosque', KE: 'savanna', TZ: 'savanna', UG: 'savanna', RW: 'jungle', ET: 'savanna', ZA: 'savanna', NA: 'camel', BW: 'savanna', ZW: 'waterfall', ZM: 'waterfall', MZ: 'beach', MG: 'jungle', MU: 'beach', SC: 'beach', GH: 'beach', NG: 'skyline', SN: 'beach', CI: 'skyline', CM: 'jungle', CD: 'jungle', CG: 'jungle', GA: 'jungle', AO: 'savanna', SD: 'pyramid', ER: 'camel', DJ: 'camel', SO: 'camel',
    MX: 'pyramid', GT: 'pyramid', BZ: 'beach', CR: 'jungle', PA: 'skyline', CU: 'oldtown', JM: 'beach', DO: 'beach', BS: 'beach', BR: 'jungle', AR: 'oldtown', CL: 'snowmountain', PE: 'mountain', BO: 'mountain', EC: 'volcano', CO: 'mountain', VE: 'waterfall', UY: 'oldtown', PY: 'waterfall', FJ: 'island', PF: 'island', WS: 'island', TO: 'island', VU: 'volcano', PG: 'jungle', GL: 'snowmountain', AQ: 'snowmountain' };
  // Sight names → landscape / heritage icon (Chinese or English words)
  const SIGHT_RULES = [
    [/喀斯特|karst|漓江|阳朔|石林|天坑|溶洞|天生三桥|小七孔/i, 'karst'], [/沙漠|desert|沙丘|dune|鸣沙山|月牙泉|雅丹|戈壁|gobi/i, 'camel'], [/草原|grassland|steppe|prairie|牧场/i, 'yurt'],
    [/雪山|snow mountain|glacier|冰川|冰湖|珠峰|everest|alps|阿尔卑斯/i, 'snowmountain'], [/瀑布|waterfall|falls\b/i, 'waterfall'], [/峡谷|canyon|gorge|大峡谷|丹霞|danxia/i, 'canyon'], [/火山|volcano|caldera/i, 'volcano'],
    [/温泉|hot spring|onsen/i, 'hotspring'], [/滑雪|ski\b/i, 'ski'], [/海滩|沙滩|beach|海湾|bay\b|天涯海角|珊瑚|coral/i, 'beach'], [/岛|island|屿/i, 'island'], [/热带雨林|rainforest|jungle|雨林/i, 'jungle'],
    [/长城|great wall/i, 'greatwall'], [/天坛|temple of heaven/i, 'tiantan'], [/布达拉|potala|寺院|monastery|藏|tibet/i, 'tibet'], [/古镇|水乡|water town|ancient town|老街|古村|古城(?!墙)/i, 'watertown'], [/城墙|city wall|城门|古城/i, 'citywall'],
    [/园林|classical garden|拙政园|留园|humble administrator/i, 'garden'], [/故宫|palace|宫|殿|forbidden city|避暑山庄/i, 'palace'], [/塔|pagoda/i, 'pagoda'], [/熊猫|panda/i, 'panda'], [/森林|forest|林海|woods/i, 'forest'],
    [/石柱|peak forest|pillars|武陵源|张家界|天子山|袁家界/i, 'pillars'], [/\b(mount|mountain|peak|mt\.?)\b|山(?!庄|海关|城)|峰/i, 'mountain'], [/湖|lake|loch|泊|错/i, 'lake'],
    [/大教堂|cathedral|教堂|church|basilica|minster|abbey|duomo|notre|sagrada/i, 'cathedral'], [/城堡|castle|schloss|château|chateau|fortress|kremlin|alcázar/i, 'castle'], [/清真寺|mosque|minaret|masjid/i, 'mosque'], [/金字塔|pyramid/i, 'pyramid'],
    [/鸟居|torii|神社|shrine/i, 'torii'], [/佛塔|stupa|wat\b|pagoda/i, 'stupa'], [/风车|windmill|molen/i, 'windmill'], [/竞技场|colosseum|amphitheat|arena/i, 'colosseum'], [/卫城|acropolis|parthenon|神庙|temple of|forum/i, 'classical'],
    [/埃菲尔|eiffel/i, 'eiffel'], [/大本钟|big ben|clock tower|钟楼/i, 'bigben'], [/穹顶|dome|大教堂圆顶|basilica/i, 'dome'], [/灯塔|lighthouse/i, 'lighthouse'], [/港|harbour|harbor|码头|pier|wharf/i, 'harbour'], [/大桥|bridge|brücke|pont\b/i, 'bridge'],
    [/电视塔|tv tower|观光塔|观景塔|明珠|canton tower|skytree|sky tower|cn tower/i, 'tower'], [/自由女神|statue|雕像/i, 'liberty'], [/歌剧院|opera house/i, 'opera'], [/摩天|skyline|cbd|金融|financial/i, 'skyline'],
  ];
  const norm = s => String(s || '').toLowerCase().replace(/\s+/g, ' ').replace(/[,.'’]/g, m => m === '’' ? "'" : m).trim();
  function byCity(place) {
    const en = norm(place.city?.en), zh = String(place.city?.zh || '').replace(/(市|地区|自治州|州|盟|县|区)$/, '');
    if (CITY[en]) return CITY[en];
    const enBare = en.replace(/ (city|shi|prefecture|county|district)$/, ''); if (CITY[enBare]) return CITY[enBare];
    if (zh && CITY[zh]) return CITY[zh];
    for (const k of Object.keys(CITY)) if (/[一-鿿]/.test(k) && zh && (zh.startsWith(k) || k.startsWith(zh)) && Math.min(k.length, zh.length) >= 2) return CITY[k];
    return '';
  }
  function bySights(place) {
    const votes = {};
    for (const g of place.sights || []) {
      const name = (g.name?.zh || '') + ' ' + (g.name?.en || '');
      const natural = (g.tags || []).some(t => t === 'wh-natural' || t === 'national-park');
      for (const [re, k] of SIGHT_RULES) if (re.test(name)) { votes[k] = (votes[k] || 0) + (natural ? 2 : 1); break; }
    }
    let best = '', n = 0; for (const [k, v] of Object.entries(votes)) if (v > n) { best = k; n = v; }
    return best;
  }
  function autoIcon(place) {
    const cc = String(place.cc || '').toUpperCase();
    return byCity(place) || bySights(place) || COUNTRY[cc] || (cc === 'CN' ? 'skyline' : EUROPE.includes(cc) ? 'oldtown' : 'city');
  }
  // The icon key for a place: the explicit choice, the home icon for places lived in, else automatic
  function iconKey(place) {
    if (place.icon && ICONS[place.icon]) return place.icon;
    if (place.trip === 'lived' && !place.academic) return 'lived';
    return autoIcon(place);
  }
  const svg = key => (ICONS[key] || ICONS.city).svg;
  const label = (key, lang) => { const i = ICONS[key] || ICONS.city; return lang === 'zh' ? i.zh : i.en; };
  window.CityIcons = { ICONS, KEYS, iconKey, autoIcon, svg, label, CITY, COUNTRY };
})();
